### ISSUE TITLE
Skin no longer working

### ISSUE THREAD

**Issue by bitpushr** [DavidFW1960/Aussie-Broadband-Usage-Meter#28]
AussieBroadband recently changed the backend of their website and such, and since then the skin has stopped working. Specifically, since December 9th at 10:39pm.
Days Remaining has started working again in the last couple of days, but data used is not and the dates/times are also still stuck.

**Comment by DavidFW1960** [comment]
I'm not with abb anymore but I'll give you a couple of suggestions when I'm back home in a few days

**Comment by bitpushr** [comment]
> I'm not with abb anymore but I'll give you a couple of suggestions when I'm back home in a few days

No problems :)

**Comment by protogen** [comment]
I'm not with ABB anymore either however my parents are.  I have tested the skin (v0.82) using their account and it is working correctly for me.

![ABBUsage](https://user-images.githubusercontent.com/3028907/147492549-6105f26f-d80e-4dfd-a261-f3c1cce76603.gif)

I have also tested using a bash script - this also works correctly for me.

@bitpushr I would suggest completely clearing out the skin data files and then refresh the skin.  This will trigger asking for your username and password again (a new cookie and refresh token will be obtained) and will redo the skin setup.

Delete the folder ```C:\Users\%USERNAME%\AppData\Roaming\Rainmeter-ABB``` then refresh the skin.

**Comment by bitpushr** [comment]
> @bitpushr I would suggest completely clearing out the skin data files and then refresh the skin. This will trigger asking for your username and password again (a new cookie and refresh token will be obtained) and will redo the skin setup.
> 
> Delete the folder `C:\Users\%USERNAME%\AppData\Roaming\Rainmeter-ABB` then refresh the skin.

Looks like that's done it, at least initially. Will leave it for a day or so to ensure it's still refreshing properly and then will close the comment if all's well. Cheers :)

**Comment by DavidFW1960** [comment]
Thanks for your input @protogen 
Look forward to your feedback @bitpushr

**Comment by protogen** [comment]
> Thanks for your input @protogen

No problem @DavidFW1960.  Happy to help.  I guessed from your comment you're away holidaying at the moment.  :slightly_smiling_face:

@bitpushr Are you able to provide more detail on your comment "**AussieBroadband recently changed the backend of their website**"?

From the testing I've done using the skin and the bash script, I haven't noticed or detected any backend change.  I'm curious to understand better.  Thanks.

**Comment by bitpushr** [comment]
> Thanks for your input @protogen Look forward to your feedback @bitpushr

Looks like all is still good so far; stats are back to updating as they should :)

> > Thanks for your input @protogen
> 
> No problem @DavidFW1960. Happy to help. I guessed from your comment you're away holidaying at the moment. 🙂
> 
> @bitpushr Are you able to provide more detail on your comment "**AussieBroadband recently changed the backend of their website**"?
> 
> From the testing I've done using the skin and the bash script, I haven't noticed or detected any backend change. I'm curious to understand better. Thanks.

They've moved from Wordpress for their website architecture to a wholly from-scratch implementation. For example, viewing the URL of an image on their website used to have '/wp-content/' in the URL but it no longer does. They also had some web developer job openings a while back specifically for doing this.
E.g: https://www.aussiebroadband.com.au/assets/logos/aussie_logo_bgb_white.png
vs
https://web.archive.org/web/20210226055354im_/https://www.aussiebroadband.com.au/wp-content/uploads/2019/09/router-icon.png

Either way, looks like things are back to working as they should. I probably should've re-initialised the skin as a troubleshooting step, but figured (incorrectly it seems) that something needed to be updated with the recent website changes :)
Happy to have this closed unless anyone wants to weigh in further.

**Comment by protogen** [comment]
Glad to hear things appear to be working normally again.  And thanks for the detail on the website change.  It's helpful info just in case something does break with the skin in the near term.

> I probably should've re-initialised the skin as a troubleshooting step, but figured (incorrectly it seems) that something needed to be updated with the recent website changes :)

No problem.  I've done the same thing myself (linking coincidental things as causal).  🙂 

> Happy to have this closed unless anyone wants to weigh in further.

Nothing further from me.  Over to you @DavidFW1960.

**Comment by DavidFW1960** [comment]
Soiunds good to me. Thanks Craig
