### ISSUE TITLE
ABBUsage v0.82 vbscript error on Win11 with RainMeter 4.5.18.3727 (64-bit)

### ISSUE THREAD

**Issue by subi75** [DavidFW1960/Aussie-Broadband-Usage-Meter#30]
I've been running ABBUsge v0.82 with Rainmeter 4.5.18.3727 (64bit) since both version were released on a Win11 x64 system now for the past 12 months with no issue, but just this week on boot up the ABBUsage skin has started to error with the below vbscript error:
Type mismatch: '[ string "Set-Cookie myaussie"]'
It also has a code error of 800A000D
It references Line 358, Char 5 in the ABB-Usage.vbs file.
refer attached screenshot of the error window
![image](https://github.com/DavidFW1960/Aussie-Broadband-Usage-Meter/assets/29177909/b09a536d-7d16-4b45-b4f0-59405fa27889)

Of note, I have not made any modifications to the ABB-Usage or Rainmeter in months (actually not since installing it on this current Win11 build about 12 months ago). The only recent system modification was Microsoft monthly patch updates (my system is currently fully up to date as of the May 2024 patch releases from MS).

I am also aware that my mother, who also uses the same versions of ABBUsage & Rainmeter started to experience the same errors earlier in the week (prior to MS releasing their May 2024 patches).

Ive also generated the attached rainmeter debug log file as well, but I'm unsure what in it would be of assistance as I dont see it capturing the vbs error
[Rainmeter.log](https://github.com/DavidFW1960/Aussie-Broadband-Usage-Meter/files/15359746/Rainmeter.log)

**Comment by DavidFW1960** [comment]
I will take a look at this but the guy who wrote the vbs isnt using ABB anymore and neither am I. It looks like maybe ABB has changed their data structure

**Comment by protogen** [comment]
I'm still around, David, and still receiving emails from this project.  I'm happy to have a look at it.  Let me know.

Also, I have a relative who is an ABB customer.  I can use their account to test the code.  :-)

**Comment by DavidFW1960** [comment]
> I'm still around, David, and still receiving emails from this project. I'm happy to have a look at it. Let me know.
> 
> Also, I have a relative who is an ABB customer. I can use their account to test the code. :-)

That would be great if you can check it out. Looks like likely a vbs issue?

**Comment by protogen** [comment]
Yes, definitely a VBS issue.  My first impression is it might be a possible change in the way ABB are delivering cookies.

I'll do some testing.  Once I have an understanding of the cause I'll report back with some info.  :-)

**Comment by protogen** [comment]
It is what I suspected.  ABB have changed the text formatting of their cookie.

Specifically, they changed the date format of the cookie expiry.  The change is causing a regex to fail.  The regex is not extracting the cookie expiry date correctly from the HTTP response header.

I have modified the regex, tested it and the code is now working as expected.  No further errors.  :-)

@DavidFW1960 I'll put the new version in a zip file and email it to you (I still have your email address).

**Comment by protogen** [comment]
@subi75

To get your skin working again you will need to obtain a new ABB auth cookie.  The easiest way to do that is to "clean" your current skin configuration.  Instructions below.

1. Once David has released the new skin version, install it (this must happen first)
2. Clean your skin configuration
    - Go to the location shown below (Note: **\<username\>** is your Windows username)
    - C:\\Users\\**\<username\>**\\Documents\\Rainmeter\\Skins\\ABBUsage\\@Resources\\Scripts\\
    - Double click on **ABB-Clean** to execute it (it will clean your skin config)
3. Refresh the ABBUsage skin (this will trigger the skin setup, or it may trigger on its own)
4. Enter your ABB username and password (a new ABB auth cookie will be obtained)
5. Answer the remaining skin setup questions
6. Refresh your skin a couple of times (until it displays correctly)

Please let us know how you go.  :-)

**Comment by DavidFW1960** [comment]
Thanks Craig. I’ll get this out tomorrow afternoon. Many thanks mate

**Comment by DavidFW1960** [comment]
0.83 should resolve this issue. Please check and comment here to confirm.
https://github.com/DavidFW1960/Aussie-Broadband-Usage-Meter/blob/master/Aussie%20Broadband%20Usage%200.83.rmskin
