### ISSUE TITLE
Update instructions minor correction required

### ISSUE THREAD

**Issue by subi75** [DavidFW1960/Aussie-Broadband-Usage-Meter#31]
Thanks for the update to 0.83 in response to my previous issue raised on Friday. Howver, during the attempt to install the skin update on my mother's PC, it prompts with the below dialog, whereas your install documentation states "Rainmeter v4.1 (or higher)" is required:
![image](https://github.com/DavidFW1960/Aussie-Broadband-Usage-Meter/assets/29177909/1e1635d2-4c7b-47e5-a538-4cfd39e6ddbc)
Obviously to fix this I just had to upgrade the version of Rainmeter on her laptop from Rainmeter's site, but I thought I would bring this to your attention in respect to the install instructions in your ReadMe.md

Note - The required version in the above dialog is the current (latest) version from Rainmeter's site as of this post

I'm not expecting any response to this, so happy for you to close the issue task whenever you want

**Comment by DavidFW1960** [comment]
Thanks. I'll fix the readme.
